# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 
  - task: DotNetCoreCLI@2
  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: 'nt19.unoeuro.com'
      username: 'pmuk-test.dk'
      password: 'pF95Agb3HkGrdBxfzh6m'
      rootDirectory: '/public_html/'
      filePatterns: '**'
      remoteDirectory: '/upload/$(Build.BuildId)/'
      clean: true
      preservePaths: false
      trustSSL: false
  inputs:
    command: 'build'
    projects: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
