# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PMUKTest CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build ⛏️

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build with dotnet
        run: dotnet build --no-restore -c Release
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: dotnet Publish
        run: dotnet publish -c Release --no-restore -o ./Release --sc true --runtime win-x86 -p:PublishTrimmed=true
        
      
        
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    
     

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: "nt19.unoeuro.com"
          username: pmuk-test.dk
          password: ${{ secrets.ftp_password }}
          localDir: "Release"
          server-dir: "/public_html/"
